#!/usr/bin/with-contenv bash

# Add intel apt package registries
if [ ! -f "/etc/apt/sources.list.d/intel-non-free.list" ]; then
    echo "**** Add Intel non free repository ****"
    curl -L https://repositories.intel.com/graphics/intel-graphics.key | apt-key add -
    echo 'deb [arch=amd64] https://repositories.intel.com/graphics/ubuntu focal main' >> /etc/apt/sources.list.d/intel-non-free.list
fi